In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1 / (1+np.exp(-x))

In [3]:
def numerical_derivatitve(f, x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        
        tmp_val = x[idx]
        
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)
        
        grad[idx] = (fx1-fx2) / (2*delta_x)
         
        x[idx] = tmp_val
        it.iternext()
        
    return grad

In [4]:
class LogicGate:
    def __init__(self, gate_name, xdata, tdata):
        self.name = gate_name
        self.__xdata = xdata
        self.__tdata = tdata
        
        self.__xdata = xdata.reshape(4, 2) # 4개 입력(입력층), 2개 출력(은닉층)
        self.__tdata = tdata.reshape(4, 1)
        
        self.__W2 = np.random.rand(2, 6) # 2개 입력, 6개 출력
        self.__b2 = np.random.rand(6)
        
        self.__W3 = np.random.rand(6, 1) # 6개 입력, 1개 출력
        self.__b3 = np.random.rand(1)
        
        self.__learning_rate = 1e-2
        
    def feed_forward(self):
        delta = 1e-7
        
        z2 = np.dot(self.__xdata, self.__W2)+self.__b2
        a2 = sigmoid(z2)
        
        z3 = np.dot(a2, self.__W3)+self.__b3
        y = sigmoid(z3)
        
        return -np.sum(self.__tdata*np.log(y+delta)+(1-self.__tdata)*np.log((1-y)+delta))
    
    def train(self):
        f = lambda x: self.feed_forward()
        print("Initial loss function:", self.feed_forward())
        
        for step in range(10001):
            self.__W2 -= self.__learning_rate*numerical_derivatitve(f, self.__W2)
            self.__b2 -= self.__learning_rate*numerical_derivatitve(f, self.__b2)
            
            self.__W3 -= self.__learning_rate*numerical_derivatitve(f, self.__W3)
            self.__b3 -= self.__learning_rate*numerical_derivatitve(f, self.__b3)
            
            if step % 400 == 0:
                print('step:', step, 'loss value:', self.feed_forward())
    
    def predict(self, xdata):
        z2 = np.dot(xdata, self.__W2) + self.__b2
        a2 = sigmoid(z2)
        
        z3 = np.dot(a2, self.__W3) + self.__b3
        y = sigmoid(z3)
        
        if y >= 0.5 :
            result = 1
        else :
            result = 0
        return y, result

In [5]:
xdata = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
tdata = np.array([0, 1, 1, 0])
XOR_obj = LogicGate('XOR_GATE', xdata, tdata)
XOR_obj.train()

Initial loss function: 6.412454287810658
step: 0 loss value: 6.2735799824448355
step: 400 loss value: 2.7638860744528757
step: 800 loss value: 2.758867398295165
step: 1200 loss value: 2.7525689026126834
step: 1600 loss value: 2.744219628897974
step: 2000 loss value: 2.732830936136835
step: 2400 loss value: 2.717148746819858
step: 2800 loss value: 2.695659371567448
step: 3200 loss value: 2.6666658475459823
step: 3600 loss value: 2.6284278694205185
step: 4000 loss value: 2.57935720809772
step: 4400 loss value: 2.518301154640197
step: 4800 loss value: 2.4449063944835827
step: 5200 loss value: 2.359812414752815
step: 5600 loss value: 2.264260910067919
step: 6000 loss value: 2.159072543461247
step: 6400 loss value: 2.043520325474544
step: 6800 loss value: 1.9147851505327362
step: 7200 loss value: 1.768631621148367
step: 7600 loss value: 1.6018712337970062
step: 8000 loss value: 1.4162169732589345
step: 8400 loss value: 1.2209500358426835
step: 8800 loss value: 1.0308831290682066
step: 9200 

In [6]:
# XOR Gate prediction
test_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
for data in test_data:
    print(XOR_obj.predict(data))
    

(array([0.09374843]), 0)
(array([0.86639358]), 1)
(array([0.86523975]), 1)
(array([0.19074075]), 0)
