In [1]:
import numpy as np

In [2]:
load_data = np.loadtxt('data/data-01-test-score.csv', delimiter=",", dtype=np.float32)

In [3]:
x_data = load_data[:,:-1]
t_data = load_data[:,[-1]]

print(x_data)
print(t_data)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]]
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [12]:
W = np.random.rand(3, 1)
b = np.random.rand(1)
print(W, b)

[[0.63120428]
 [0.71253073]
 [0.64742567]] [0.33385839]


In [5]:
def loss_func(x, t):
    y = np.dot(x, W) + b
    
    return(np.sum((t-y)**2)) / len(x)

In [6]:
def numerical_derivatitve(f, x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    
#     print('x =', x)
#     print('grad =', grad)
#     print('='*50)
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        
#         print('idx =', idx,'x[idx] =', x[idx])
        
        tmp_val = x[idx]
        
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)
        
        grad[idx] = (fx1-fx2) / (2*delta_x)
         
#         print('grad[idx] =', grad[idx])
#         print('grad =', grad)
#         print('='*50)
        x[idx] = tmp_val
        it.iternext()
        
    return grad

In [7]:
def predict(x):
    y = np.dot(x, W)+b
    
    return y

In [13]:
learning_rate = 1e-6

f = lambda x : loss_func(x_data, t_data)

print("Initial error value:", loss_func(x_data, t_data), "Initial W = ", W, "Initial b=", b)

for step in range(10001):
    W -= learning_rate*numerical_derivatitve(f, W)
    b -= learning_rate*numerical_derivatitve(f, b)
    
    if step%400==0:
        print('step =', step, 'error value=', loss_func(x_data, t_data), 'W =', W, 'b =', b)

Initial error value: 18.745025659410068 Initial W =  [[0.63120428]
 [0.71253073]
 [0.64742567]] Initial b= [0.33385839]
step = 0 error value= 18.272976612659818 W =  [[0.63159257]
 [0.71291739]
 [0.64785132]] b =  [0.33386306]
step = 400 error value= 12.403518497142262 W =  [[0.63830415]
 [0.71818771]
 [0.66512577]] b =  [0.33396177]
step = 800 error value= 12.204744497094095 W =  [[0.63534545]
 [0.71379169]
 [0.67229725]] b =  [0.33394412]
step = 1200 error value= 12.012530682572692 W =  [[0.63241883]
 [0.70948379]
 [0.67935146]] b =  [0.33392563]
step = 1600 error value= 11.82665545684464 W =  [[0.62952394]
 [0.70526233]
 [0.68629036]] b =  [0.3339063]
step = 2000 error value= 11.646904814815862 W =  [[0.6266604 ]
 [0.7011257 ]
 [0.69311591]] b =  [0.33388616]
step = 2400 error value= 11.473072080775488 W =  [[0.62382787]
 [0.69707229]
 [0.69983001]] b =  [0.33386522]
step = 2800 error value= 11.30495765524229 W =  [[0.621026  ]
 [0.69310053]
 [0.70643453]] b =  [0.33384348]
step = 3